# Generated by Django 5.0.4 on 2024-05-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
